#!/usr/bin/python3

import os
import subprocess as sp

# In each music directory, we convert all musics to .wav format
# We only convert those that haven't been converted yet

def toRaw():
    # Get file names
    files = sp.check_output(["ls"]).decode("utf8").strip().split("\n")

    # Get files that are already in wav format
    wav = []
    for f in files:
        parts = f.split(".")
        if parts[-1] == "wav":
            wav.append(''.join(parts[:-1]))

    # Get files that haven't been converted yet
    toConvert = []
    for f in files:
        parts = f.split(".")
        ext = parts[-1] # extension
        stem = ''.join(parts[:-1]) # filename without extension
        if ext != "wav" and stem not in wav:
            toConvert.append(f)

    print("Of all {} files, {} are already converted. We will convert {}.".format(
        len(files), len(files) - len(toConvert), len(toConvert))
        )

    # Convert files to wav
    for f in toConvert:
        stem = ''.join(f.split(".")[:-1])
        retval = sp.run(
            ["ffmpeg", "-i", f, # "-ab", "96k",
             "-ss", "0", "-t", "30", # Get 30 seconds, starting from 0
             "-ac", "1", "-ar", "44100", "-vn", stem + ".wav"]
            ).returncode
        if(retval != 0):
            print("Sorry, could not convert file '{}', so we will ignore it for now.".format(f))

try:
    os.chdir("./music_negative/")
except:
    print("Couldn't chdir. We are on dir: " + os.getcwd())

toRaw()

os.chdir("..")
try:
    os.chdir("./music_positive/")
except:
    print("Couldn't chdir. We are on dir: " + os.getcwd())

toRaw()

os.chdir("..")

